language: go
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/modocache/gover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - ginkgo -cover -race -v -r -randomizeAllSpecs 
  - goveralls -repotoken $REPOSITORY_TOKEN
